apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: api
  name: api-deployment
spec:
  replicas: 12
  selector:
    matchLabels:
      app: api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: zephinzer/eg-whack-a-pod:api
        imagePullPolicy: IfNotPresent
        name: api-deployment
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: Always